version: '1'

networks:
  waste-manager:
    driver: bridge
    name: waste-manager

services:
  cloud-config:
    container_name: c-cloud-config
    build:
      context: DockerFile
      dockerfile: Dockerfile-cloudconfig
    image: i-cloud-config:latest
    ports:
      - 6060:6060
    networks:
      - waste-manager
  discovery:
    container_name: c-eureka
    build:
      context: DockerFile
      dockerfile: Dockerfile-eureka
    image: i-eureka:latest
    ports:
      - 8761:8761
    networks:
      - waste-manager
  waste-manager:
    container_name: c-waste-manager
    build:
      context: DockerFile
      dockerfile: Dockerfile-waste
    image: i-waste-manager:latest
    networks:
      - waste-manager
  api-gateway:
    container_name: c-api-gateway
    build:
      context: DockerFile
      dockerfile: Dockerfile-apigateway
    image: i-api-gateway:latest
    ports:
      - 9090:9090
    networks:
      - waste-manager